[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"

[functions]
  directory = "netlify/functions"

# Authentication with Netlify Functions
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/middleware"
  status = 200
  force = true

# Exception for Netlify function files
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback after authentication (only used after middleware redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200