[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"

[functions]
  directory = "netlify/functions"

# Use a simpler approach for authentication
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/middleware"
  status = 200
  force = true
  
# SPA fallback after authentication
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200